source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.0.2'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'


# Fast and furious webserver
gem 'unicorn', '~> 4.6'

# Stylus rocks and rolls
gem 'stylus', '~> 1.0.0.beta'
gem 'stylus-source', '~> 0.33.0'
gem 'autoprefixer-rails'
gem 'fonts-rails'

# So does the newest Slim
gem 'slim', '~> 2.0'

# Use Uglifier as a compressor for JS assets
gem 'uglifier', '>= 1.3.0'

# Use jquery
gem 'jquery-rails'
gem 'autosize-rails'


# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'



# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

group :doc do
  gem 'sdoc', require: false
end

# Hero of the day
gem 'birmanizer'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
